name = "BioGenerics"
uuid = "47718e42-2ac5-11e9-14af-e5595289c2ea"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.1.0"

[deps]
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
TranscodingStreams = "0.9"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
